const fs = require('fs');
const path = require('path');

// 1. BDS (Bất động sản) - 100 per field
const bds_boicanh = [
  "Dự án căn hộ cao cấp đang hoàn thiện phần móng",
  "Căn hộ bàn giao thô chuẩn bị nhận nhà hoàn thiện",
  "Nhà phố liền kề mặt tiền đường 30m sầm uất",
  "Văn phòng công chứng quận trung tâm đông nghịt người",
  "Ngân hàng tiến hành phát mãi nhà đất nợ xấu",
  "Quán cà phê giao dịch bất động sản giờ cao điểm",
  "Khu đô thị sinh thái ven sông quy mô hàng trăm hecta",
  "Khu dân cư hiện hữu lâu đời với hạ tầng hoàn chỉnh",
  "Đất nền phân lô ven đô có sổ đỏ từng nền",
  "Nhà cấp bốn sân vườn rộng rãi vùng ngoại ô",
  "Biệt thự đơn lập kiến trúc tân cổ điển sang trọng",
  "Shophouse chân đế chung cư thuận tiện kinh doanh",
  "Phòng giao dịch sàn bất động sản ngày mở bán dự án",
  "Nhà mẫu dự án trang bị đầy đủ nội thất cao cấp",
  "Căn hộ penthouse thông tầng view toàn cảnh thành phố",
  "Đất nông nghiệp diện tích lớn quy hoạch lên thổ cư",
  "Văn phòng làm việc công ty môi giới nhà đất",
  "Chung cư mini cho thuê kín phòng tạo dòng tiền ổn định",
  "Homestay đồi thông thơ mộng ngắm sương mù sáng sớm",
  "Nhà nát hẻm ba gác quận trung tâm cần cải tạo",
  "Khu đất vườn cây ăn trái sum suê ven sông",
  "Khu nghỉ dưỡng 5 sao ven biển miền Trung",
  "Căn hộ cao cấp ven sông đón gió tự nhiên thoáng mát",
  "Phòng khách gia đình quây quần bàn tính chuyện mua nhà",
  "Bàn ăn gia đình sôi nổi thảo luận chọn căn hộ đầu tiên",
  "Quán trà sữa góc phố nơi môi giới gặp gỡ khách hàng",
  "Hội trường hội thảo chuyên sâu về chu kỳ bất động sản",
  "Công viên nội khu dự án rợp bóng mát cây xanh",
  "Cầu vượt và nút giao thông ngã tư vừa thông xe",
  "Khu đất nông nghiệp giáp ranh khu công nghiệp lớn",
  "Nhà phố hẻm xe hơi tránh nhau thông thoáng",
  "Khu chung cư cũ tập thể đang chờ cải tạo quy hoạch",
  "Nhà nát chủ cần bán nhanh giải quyết việc tài chính",
  "Kho bãi nhà xưởng sản xuất quy mô lớn ngoại thành",
  "Nhà phố một trệt hai lầu vừa xây dựng hoàn thiện",
  "Căn hộ duplex thông tầng phong cách hiện đại",
  "Vùng đất trù phú ven sông phù hợp làm trang trại",
  "Vùng kinh tế trọng điểm đang mở rộng hạ tầng giao thông",
  "Tuyến phố đi bộ sầm uất tập trung khách du lịch",
  "Khu biệt thự compound khép kín bảo vệ an ninh 24/7",
  "Dự án nhà ở xã hội đáp ứng nhu cầu ở thực",
  "Khu condotel nghỉ dưỡng sát bờ biển thơ mộng",
  "Văn phòng làm việc độc lập của nhóm môi giới tự do",
  "Quán ăn vỉa hè giờ tan tầm nơi người dân bàn chuyện đất đai",
  "Dãy phòng trọ công nhân đông đúc kín khách thuê",
  "Trung tâm thương mại sầm uất chuẩn bị khai trương",
  "Trạm thu phí cao tốc mới rút ngắn thời gian di chuyển",
  "Khu đất đấu giá của nhà nước đông kín người tham dự",
  "Mảnh đất góc hai mặt tiền đắc địa buôn bán",
  "Căn biệt thự kiến trúc châu Âu uy nghi tráng lệ",
  "Khu tái định cư hạ tầng đồng bộ đường nhựa rộng rãi",
  "Nhà vườn sinh thái nghỉ dưỡng cuối tuần của gia đình",
  "Khu du lịch sinh thái ven hồ cảnh quan thiên nhiên trong lành",
  "Dự án đất nền sổ sẵn pháp lý an toàn tuyệt đối",
  "Tuyến phố thời trang trung tâm tấp nập người qua lại",
  "Căn hộ studio thiết kế thông minh cho người độc thân",
  "Phòng họp ban giám đốc công ty địa ốc thảo luận chiến lược",
  "Khu công nghệ cao tập trung hàng vạn chuyên gia làm việc",
  "Cánh đồng lúa chuẩn bị chuyển đổi quy hoạch khu đô thị",
  "Dãy nhà phố liền kề phong cách tân cổ điển đồng bộ",
  "Khu dân cư mới hình thành ven trục đường huyết mạch",
  "Tuyến đường vành đai đang khẩn trương thi công ngày đêm",
  "Bến du thuyền sang trọng tấp nập tàu thuyền cập bến",
  "Sân golf chuẩn quốc tế thu hút giới doanh nhân gặp gỡ",
  "Sảnh đón khách chung cư hạng sang trang hoàng lộng lẫy",
  "Nhà phố hẻm nội bộ an ninh yên tĩnh tuyệt đối",
  "Mảnh đất trống vị trí đẹp đang chờ tăng giá",
  "Khu căn hộ dịch vụ cao cấp dành cho chuyên gia nước ngoài",
  "Căn hộ hướng biển đón ánh bình minh rạng rỡ",
  "Khu nghỉ dưỡng sinh thái trên đồi view thung lũng",
  "Xưởng thiết kế kiến trúc nội thất ngập tràn bản vẽ 3D",
  "Công trường thi công dự án tấp nập máy móc hoạt động",
  "Quán bia hơi bình dân nơi các nhà đầu tư trao đổi thông tin",
  "Nhà hàng cao cấp tiếp đón đối tác ký kết hợp đồng",
  "Chợ truyền thống nhộn nhịp nằm ngay đối diện dự án",
  "Khu du lịch biển nổi tiếng thu hút hàng triệu lượt khách",
  "Đất mặt tiền quốc lộ xe cộ lưu thông đông đúc",
  "Căn nhà cũ vừa hoàn thiện nâng cấp sửa chữa hiện đại",
  "Nhà phố phong cách tối giản kiểu Nhật Bản tinh tế",
  "Căn hộ smarthome tích hợp công nghệ điều khiển tự động",
  "Dự án ven biển đón đầu quy hoạch phát triển du lịch",
  "Khu vực quy hoạch sân bay quốc tế chuẩn bị khởi công",
  "Khu đất đối diện cổng chính khu công nghiệp lớn",
  "Nhà cũ giá tốt phù hợp gia đình trẻ tự sửa sang",
  "Biệt thự liền kề với khoảng sân vườn trước sau thoáng đãng",
  "Căn hộ officetel vừa làm việc vừa lưu trú linh hoạt",
  "Nhà phố hẻm thông bàn cờ xe ô tô ra vào thuận tiện",
  "Quần thể shophouse thương mại ven biển đón khách mua sắm",
  "Khu đất quy hoạch trung tâm hành chính mới của tỉnh",
  "Tuyến đường sắt đô thị trên cao sắp vận hành thử nghiệm",
  "Khu vực vùng ven chuẩn bị sáp nhập vào thị xã",
  "Chung cư cao tầng view trọn vẹn pháo hoa đêm lễ hội",
  "Khu đất đồi trồng cây dược liệu khí hậu mát mẻ",
  "Nhà cấp bốn có gác lửng đúc kiên cố xinh xắn",
  "Nhà phố hai mặt thoáng đón trọn ánh sáng tự nhiên",
  "Biệt thự phong cách Địa Trung Hải rực rỡ sắc màu",
  "Khu đất trang trại ven suối nước chảy róc rách quanh năm",
  "Đại đô thị thông minh all in one đầy đủ trường học bệnh viện",
  "Hội trường đấu giá đất công khai kết quả trúng thầu",
  "Khu đô thị ven vịnh biển quy hoạch đồng bộ đẳng cấp"
];

const bds_nhanvat = [
  "Môi giới bất động sản lâu năm giàu kinh nghiệm thực chiến",
  "Cặp vợ chồng trẻ tích cóp nhiều năm mua căn nhà đầu tiên",
  "Nhà đầu tư F0 mới tham gia thị trường còn nhiều bỡ ngỡ",
  "Chủ đất lớn tuổi cần bán gấp chia tài sản cho các con",
  "Khách hàng mua nhà lần đầu cẩn thận kiểm tra pháp lý",
  "Nhà đầu tư cá mập chuyên săn lùng bất động sản ngộp giá",
  "Chuyên gia phong thủy nhà ở có tiếng trong giới bất động sản",
  "Kiến trúc sư trưởng tâm huyết với thiết kế không gian xanh",
  "Luật sư chuyên tư vấn xử lý tranh chấp và thẩm định sổ đỏ",
  "Mẹ bỉm sữa kinh doanh căn hộ cho thuê tạo dòng tiền thụ động",
  "Việt kiều về nước tìm kiếm cơ hội đầu tư đất đai quê hương",
  "Nhóm bạn thân hùn vốn mua chung lô đất nền vùng ven",
  "YouTuber chuyên review nhà đẹp và bất động sản triệu đô",
  "Cán bộ ngân hàng phụ trách thẩm định hồ sơ vay thế chấp",
  "Chủ thầu xây dựng dày dạn kinh nghiệm cam kết đúng tiến độ",
  "Đại gia bất động sản sở hữu chuỗi khách sạn và biệt thự biển",
  "Chủ căn hộ dịch vụ chia sẻ bí quyết luôn lấp đầy phòng",
  "Chuyên gia phân tích chu kỳ kinh tế và thị trường nhà đất",
  "Môi giới có tâm tư vấn giải pháp tài chính vừa sức khách",
  "Chủ nhà trọ thân thiện luôn hỗ trợ người thuê mùa khó khăn",
  "Kỹ sư giám sát chất lượng thi công tại công trường dự án",
  "Chủ doanh nghiệp nhỏ tìm mua shophouse mở văn phòng đại diện",
  "Chàng trai độc thân đam mê căn hộ studio phong cách tối giản",
  "Cô gái 25 tuổi tự tay mua căn hộ chung cư bằng tiền tích lũy",
  "Chuyên viên định giá tài sản độc lập giàu kinh nghiệm",
  "Nhà đầu tư yêu thiên nhiên thích cuộc sống bỏ phố về vườn",
  "Bác sĩ trẻ tìm mua căn hộ gần bệnh viện để tiện đi lại",
  "Giáo viên về hưu dùng tiền tiết kiệm mua mảnh đất dưỡng già",
  "Chủ vườn lan đột biến chuyển hướng sang đầu tư đất nền",
  "Đại diện ban quản trị chung cư bảo vệ quyền lợi cư dân",
  "Nhà sáng lập công ty công nghệ đầu tư chuỗi homestay nghỉ dưỡng",
  "Chủ tiệm vàng tích trữ tài sản bằng việc mua gom đất mặt phố",
  "Cặp đôi sắp cưới cùng nhau lên kế hoạch vay vốn mua tổ ấm",
  "Trưởng phòng kinh doanh sàn địa ốc truyền lửa cho đội ngũ",
  "Chuyên viên đo đạc địa chính hỗ trợ xác định ranh giới thửa đất",
  "Nhà đầu tư lướt sóng chuyên đón đầu các dự án mở bán đợt 1",
  "Khách hàng khó tính yêu cầu kiểm tra từng chi tiết nội thất",
  "Cụ ông 70 tuổi quyết định giữ đất vườn làm của để dành cho cháu",
  "Bà chủ chuỗi nhà hàng mua đất xây biệt phủ sinh thái",
  "Người mua nhà ở thực ưu tiên vị trí gần trường học cho con",
  "Chuyên gia quy hoạch đô thị chia sẻ góc nhìn hạ tầng tương lai",
  "Nhà đầu tư chuyên săn nhà nát về sửa sang bán lại kiếm lời",
  "Trưởng ban quản lý dự án đô thị kiểm tra tiến độ bàn giao",
  "Chủ doanh nghiệp xuất nhập khẩu mua đất xây kho bãi logistic",
  "Nhiếp ảnh gia chuyên chụp ảnh kiến trúc và không gian nội thất",
  "Chủ xưởng gỗ nội thất tư vấn phương án thi công căn hộ",
  "Nhân viên văn phòng tranh thủ cuối tuần đi xem đất nền tỉnh lẻ",
  "Bác tài xế công nghệ tích góp tiền mua miếng đất vùng ngoại ô",
  "Chị tiểu thương chợ đầu mối đầu tư vào dãy phòng trọ cho thuê",
  "Nhà đầu tư trung niên chuộng phân khúc đất nền có sổ đỏ trao tay",
  "Chuyên viên tư vấn bảo hiểm kiêm đầu tư bất động sản cá nhân",
  "Cựu chiến binh gìn giữ mảnh đất hương hỏa của gia đình",
  "Chủ khách sạn mini ven biển chia sẻ bài học kinh doanh mùa dịch",
  "Nhà đầu tư cá nhân thận trọng chỉ mua tài sản có sẵn sổ hồng",
  "Người sáng tạo nội dung quay video thực tế các dự án bất động sản",
  "Chủ chuỗi cà phê tìm kiếm mặt bằng góc ngã tư kinh doanh đắc địa",
  "Kiểm toán viên phân tích bảng cân đối dòng tiền khi vay mua nhà",
  "Cặp vợ chồng trung niên muốn đổi từ nhà ống sang căn hộ cao cấp",
  "Chàng kỹ sư IT làm việc từ xa muốn sống ở căn hộ ven biển",
  "Chủ gara ô tô mua đất mở rộng mặt bằng xưởng dịch vụ",
  "Môi giới mới vào nghề đầy nhiệt huyết và tinh thần học hỏi",
  "Nhà đầu tư dài hạn tin tưởng vào tiềm năng tăng giá của đất ven đô",
  "Khách hàng nhận bồi thường đất giải phóng mặt bằng tái định cư",
  "Chuyên viên phòng tài nguyên môi trường hướng dẫn thủ tục sang tên",
  "Chủ farmstay nông nghiệp công nghệ cao kết hợp du lịch trải nghiệm",
  "Vợ chồng Việt kiều mong muốn an dưỡng tuổi già tại quê hương",
  "Nữ doanh nhân thành đạt tự thưởng cho mình căn biệt thự view hồ",
  "Nhà đầu tư ưa chuộng bất động sản ven các khu công nghiệp lớn",
  "Người mua căn hộ lần 2 với nhiều kinh nghiệm chọn chủ đầu tư",
  "Môi giới địa phương am hiểu tường tận từng ngõ ngách khu vực",
  "Chủ cửa hàng vật liệu xây dựng liên kết với các nhà thầu lớn",
  "Chuyên gia tài chính cảnh báo rủi ro khi dùng đòn bẩy quá mức",
  "Nhà đầu tư gom đất trồng cây lâu năm chờ chuyển đổi mục đích",
  "Bà mẹ đơn thân nỗ lực làm việc mua căn chung cư cho hai mẹ con",
  "Chủ đầu tư tâm huyết phát triển không gian sống chuẩn xanh",
  "Khách hàng tìm kiếm căn hộ có thiết kế ban công rộng thoáng mát",
  "Cán bộ quy hoạch chia sẻ thông tin về các tuyến đường vành đai",
  "Chuyên viên ngân hàng tư vấn gói vay lãi suất ưu đãi cho người trẻ",
  "Nhà đầu tư gom đất mặt hồ xây dựng khu cắm trại glamping",
  "Chủ căn hộ dịch vụ cao cấp hướng đến tệp khách lưu trú dài hạn",
  "Bác nông dân thuần phác có đất nằm trong diện quy hoạch đô thị",
  "Kỹ sư cơ điện kiểm tra hệ thống phòng cháy chữa cháy tòa nhà",
  "Nhà sưu tập nghệ thuật thiết kế biệt thự trưng bày tranh quý",
  "Gia đình nhiều thế hệ tìm kiếm căn nhà phố rộng rãi sum vầy",
  "Nhà đầu tư chuyên mua gom đất thổ cư diện tích nhỏ dễ thanh khoản",
  "Môi giới chuyên phân khúc biệt thự nghỉ dưỡng và dinh thự cao cấp",
  "Chủ trang trại bò sữa đầu tư mở rộng quỹ đất chăn thả",
  "Người mua nhà cẩn thận kiểm tra áp lực nước và cách âm căn hộ",
  "Chuyên gia thẩm định kết cấu công trình xây dựng dân dụng",
  "Nhà đầu tư có tầm nhìn đón đầu các dự án hạ tầng giao thông lớn",
  "Chủ chuỗi phòng khám nha khoa tìm mặt bằng mở chi nhánh mới",
  "Chàng trai trẻ khởi nghiệp thành công mua nhà báo hiếu bố mẹ",
  "Nhà phân tích thị trường đưa ra dự báo về xu hướng bất động sản",
  "Môi giới tự do xây dựng kênh TikTok cá nhân thu hút hàng ngàn khách",
  "Chủ xưởng may gia công mua đất mở rộng quy mô xưởng sản xuất",
  "Khách hàng quan tâm đến tiện ích trường học và khu vui chơi trẻ em",
  "Chuyên viên môi giới thương mại chuyên kết nối mặt bằng bán lẻ",
  "Nhà đầu tư chuộng bất động sản sinh thái giữ gìn sức khỏe",
  "Cặp vợ chồng làm nghề tự do chọn căn hộ có phòng làm việc riêng",
  "Nhà đầu tư thông thái luôn dự trù quỹ tài chính dự phòng an toàn"
];

const bds_hanhdong = [
  "Trực tiếp đến kiểm tra ranh giới và cột mốc thửa đất trên thực địa",
  "Đối chiếu thông tin quy hoạch tại phòng tài nguyên môi trường quận",
  "So sánh giá bán các dự án lân cận trong bán kính 3 kilomet",
  "Thương lượng trực tiếp với chủ nhà xin giảm giá 5 phần trăm",
  "Kiểm tra chất lượng hoàn thiện trần tường sàn và thiết bị vệ sinh",
  "Đọc kỹ từng điều khoản trong hợp đồng mua bán và tiến độ thanh toán",
  "Tính toán dòng tiền cho thuê và tỷ suất sinh lời hàng năm",
  "Nhờ ngân hàng thẩm định độc lập giá trị tài sản trước khi xuống tiền",
  "Khảo sát lưu lượng giao thông trước cửa nhà vào các khung giờ cao điểm",
  "Tham khảo ý kiến hàng xóm xung quanh về tình hình an ninh khu phố",
  "Kiểm tra hệ thống điện nước và khả năng chống thấm dột mùa mưa",
  "Tìm hiểu lịch sử pháp lý và tranh chấp thừa kế của bất động sản",
  "Chụp ảnh quay video chi tiết các góc căn nhà để lưu trữ đối chiếu",
  "Đàm phán kéo dài thời gian công chứng để chuẩn bị đủ dòng tiền",
  "Lái xe chạy thử từ dự án đến chỗ làm xem mất bao nhiêu phút",
  "Kiểm tra bản vẽ thiết kế thi công và giấy phép xây dựng được cấp",
  "Đặt cọc giữ chỗ ngay trong ngày mở bán để nhận chiết khấu cao nhất",
  "Thuê đơn vị kiểm định độc lập đo đạc lại diện tích sử dụng thực tế",
  "Đăng bài tìm khách thuê căn hộ trên các hội nhóm mạng xã hội",
  "Cải tạo sơn sửa lại toàn bộ ngôi nhà cũ trước khi rao bán",
  "Tham gia buổi đấu giá đất công khai và bỏ phiếu trả giá",
  "Rà soát danh mục vật liệu bàn giao đính kèm phụ lục hợp đồng",
  "Hỏi thăm thông tin quy hoạch mở rộng đường từ cán bộ địa chính",
  "Lên phương án vay vốn ngân hàng với mức trả góp vừa sức thu nhập",
  "Thiết kế lại công năng phòng ốc để tối ưu hóa không gian sinh hoạt",
  "Gặp gỡ môi giới uy tín để ký hợp đồng gửi bán độc quyền",
  "Kiểm tra áp lực nước sinh hoạt tại tầng cao nhất của tòa chung cư",
  "Đo đạc hướng nhà bằng la bàn phong thủy để bố trí phòng thờ",
  "Xem xét kỹ mức phí quản lý và các loại phí dịch vụ hàng tháng",
  "Chốt hợp đồng công chứng chuyển nhượng quyền sử dụng đất thành công",
  "Yêu cầu bên bán xuất trình bản gốc sổ đỏ và giấy xác nhận độc thân",
  "Lập bảng tính Excel chi tiết tiến độ thanh toán theo từng đợt",
  "Tìm kiếm mặt bằng shophouse phù hợp ngành hàng thời trang",
  "Khảo sát mức giá thuê phòng trọ bình quân của khu vực xung quanh",
  "Yêu cầu chủ đầu tư cung cấp biên bản nghiệm thu phòng cháy chữa cháy",
  "Lắp đặt hệ thống camera giám sát và khóa cửa vân tay thông minh",
  "Tham khảo ý kiến của luật sư về tính pháp lý hợp đồng đặt cọc",
  "Rủ bạn bè có chuyên môn xây dựng cùng đi xem nhà thẩm định giúp",
  "Đăng ký nhận thông báo mở bán đợt đầu các dự án vị trí đẹp",
  "Chuyển toàn bộ tiền cọc qua tài khoản ngân hàng có ghi rõ nội dung",
  "Đi thực địa xem nhà vào ngày mưa lớn để kiểm tra tình trạng ngập nước",
  "Tìm hiểu quy chế quản lý vận hành của ban quản trị tòa nhà",
  "Đo khoảng cách từ căn nhà đến trường học bệnh viện và chợ gần nhất",
  "Kiểm tra tình trạng thế chấp ngân hàng của bất động sản định mua",
  "Thương thảo điều khoản bảo hành nhà ở trong vòng 12 tháng đầu",
  "Lựa chọn gói nội thất thông minh tiết kiệm diện tích cho căn hộ nhỏ",
  "Theo dõi sát sao biến động lãi suất cho vay của các ngân hàng thương mại",
  "Đặt lịch hẹn làm việc với công chứng viên để chuẩn bị hồ sơ sang tên",
  "Tìm kiếm mảnh đất có vị trí nở hậu hợp phong thủy làm ăn",
  "Hỏi kỹ về tình trạng cấp sổ hồng cho các phân khu đã bàn giao",
  "Tự tay dọn dẹp trang trí lại ban công ngập tràn cây xanh và hoa",
  "Kiểm tra hệ thống thoát sàn và mùi hôi nhà vệ sinh khi xem nhà",
  "Yêu cầu chủ nhà cam kết bàn giao đầy đủ nội thất gắn tường như thỏa thuận",
  "Tận dụng đòn bẩy tài chính an toàn dưới 50 phần trăm giá trị tài sản",
  "Lập nhóm đầu tư chung chia đều quyền lợi và trách nhiệm pháp lý",
  "Kiểm tra công tơ điện nước riêng biệt cho từng phòng trọ cho thuê",
  "Tham gia các hội thảo bất động sản để mở rộng mạng lưới quan hệ",
  "Theo dõi tiến độ thi công hạ tầng đường vành đai trên báo chí chính thống",
  "Rao bán bất động sản trên các nền tảng trực tuyến kèm hình ảnh chân thực",
  "Lựa chọn căn hộ tầng trung có tầm nhìn thoáng đãng không bị che chắn",
  "Kiểm tra khả năng bắt sóng điện thoại và internet trong căn hộ",
  "Gặp trực tiếp chủ đất để thương lượng giá không qua nhiều trung gian",
  "Tìm hiểu về uy tín và năng lực tài chính của ban lãnh đạo chủ đầu tư",
  "Đăng ký nộp thuế thu nhập cá nhân và lệ phí trước bạ trực tuyến",
  "Trồng thêm cây bóng mát xung quanh hàng rào ngôi nhà vườn nghỉ dưỡng",
  "Kiểm tra độ dày cách âm của tường ngăn giữa các căn hộ kế bên",
  "Yêu cầu ban quản lý hỗ trợ thẻ đỗ xe ô tô tại tầng hầm tòa nhà",
  "Ghi chép lại nhật ký thị trường và giá giao dịch thực tế hàng tuần",
  "Tính toán khấu hao tài sản và chi phí bảo trì sửa chữa hàng năm",
  "Kiểm tra giấy tờ tùy thân của người đứng tên trên giấy chứng nhận",
  "Tư vấn giải pháp thiết kế giếng trời lấy sáng tự nhiên cho nhà phố",
  "Tìm kiếm cơ hội đầu tư tại các đô thị vệ tinh đang phát triển mạnh",
  "Xác định ranh giới thửa đất bằng thiết bị định vị vệ tinh chuyên dụng",
  "Thương lượng thanh toán tiền cọc thành 2 đợt để giảm áp lực dòng tiền",
  "Lựa chọn hướng ban công Đông Nam mát mẻ vào mùa hè ấm áp mùa đông",
  "Tham khảo bảng giá đất nhà nước mới ban hành để ước tính chi phí thuế",
  "Khảo sát nhu cầu thuê nhà của các chuyên gia tại khu công nghiệp lân cận",
  "Đăng ký gói vay ưu đãi cố định lãi suất 2 năm đầu tại ngân hàng quen",
  "Lắp đặt hệ thống điện năng lượng mặt trời áp mái cho ngôi nhà vườn",
  "Kiểm tra tiến độ xây dựng hạ tầng trường mầm non nội khu dự án",
  "Chủ động liên hệ với chủ nhà khi phát hiện bất động sản hạ giá sâu",
  "Đọc kỹ quy chế sử dụng khu vực sở hữu chung và sở hữu riêng",
  "Thuê kiến trúc sư phác thảo bản vẽ cải tạo nâng tầng cho ngôi nhà cũ",
  "Tham khảo đánh giá của cộng đồng cư dân đang sinh sống tại dự án",
  "Tổ chức buổi tiệc tân gia ấm cúng mời người thân và bạn bè đến chơi",
  "Thực hiện thủ tục giải chấp sổ đỏ tại văn phòng đăng ký đất đai",
  "Khảo sát chất lượng nước ngầm tại khu đất nông nghiệp chuẩn bị mua",
  "Thỏa thuận rõ ràng về bên chịu trách nhiệm nộp các khoản thuế phí chuyển nhượng",
  "Lắp đặt hệ thống lọc nước đầu nguồn cho toàn bộ căn biệt thự",
  "Kiểm tra khoảng lùi xây dựng theo quy chuẩn của khu đô thị mới",
  "Lựa chọn căn hộ có hai mặt thoáng để đối lưu không khí trong lành",
  "Theo dõi tiến độ hoàn thiện đường giao thông kết nối vào dự án",
  "Đặt cọc có người làm chứng và ghi biên bản bàn giao tiền chi tiết",
  "Khảo sát các tiện ích xung quanh như siêu thị chợ trạm y tế trong bán kính 1km",
  "Tận dụng góc chết dưới chân cầu thang làm tủ chứa đồ gọn gàng",
  "Đàm phán giữ lại một phần tiền đến khi nhận sổ đỏ mới thanh toán hết",
  "Tham gia nghiệm thu căn hộ cùng kỹ sư xây dựng có chứng chỉ hành nghề",
  "Gửi thông báo cho ban quản lý tòa nhà trước khi tiến hành sửa chữa",
  "Xây dựng kế hoạch tài chính trả nợ gốc và lãi đều đặn hàng tháng",
  "Kiểm tra hệ thống báo khói và đầu phun chữa cháy tự động trong căn hộ"
];

const bds_ketqua = [
  "Sở hữu căn nhà mơ ước với mức giá hợp lý và pháp lý chuẩn chỉnh",
  "Thu về khoản lợi nhuận 30 phần trăm sau một năm đầu tư đất nền",
  "Chốt hợp đồng mua bán thành công ngay trong ngày đầu tiên mở bán",
  "Cho thuê kín phòng với dòng tiền ổn định 25 triệu đồng mỗi tháng",
  "Căn hộ tăng giá 400 triệu đồng sau khi tuyến đường lớn thông xe",
  "Nhận bàn giao sổ hồng trao tay sớm hơn dự kiến của chủ đầu tư",
  "Đàm phán thành công giúp tiết kiệm được 150 triệu đồng tiền mua nhà",
  "Bảo vệ an toàn nguồn vốn tích lũy tránh được các dự án ma không phép",
  "Tạo lập được tài sản tích lũy vững chắc cho tương lai con cái sau này",
  "Tự tay thiết kế và hoàn thiện không gian sống đúng sở thích cá nhân",
  "Gia đình hòa thuận hạnh phúc trọn vẹn trong tổ ấm khang trang mới",
  "Tìm được mặt bằng kinh doanh đắc địa giúp doanh thu tăng gấp đôi",
  "Thanh khoản nhanh chóng lô đất trong vòng một tuần với giá như ý",
  "Nhận nhà mới tinh tươm đúng tiến độ cam kết trước Tết Nguyên Đán",
  "Tối ưu hóa công năng sử dụng giúp ngôi nhà luôn thông thoáng tiện nghi",
  "Tránh được rủi ro vướng quy hoạch giải tỏa nhờ kiểm tra kỹ lưỡng",
  "Được ngân hàng giải ngân nhanh chóng với gói lãi suất ưu đãi nhất",
  "Biến mảnh đất hoang sơ thành khu nhà vườn xanh mướt tràn ngập hoa trái",
  "Xây dựng được thương hiệu môi giới uy tín được khách hàng tin tưởng giới thiệu",
  "Hoàn tất thủ tục sang tên đổi sổ đỏ nhanh gọn chỉ trong 15 ngày làm việc",
  "Tận hưởng không gian sống trong lành yên tĩnh nâng cao sức khỏe gia đình",
  "Khai thác dòng tiền cho thuê vượt trội bù đắp toàn bộ tiền lãi vay ngân hàng",
  "Giúp đỡ hàng chục khách hàng an cư lập nghiệp chọn đúng căn nhà phù hợp",
  "Thoát hàng an toàn ở vùng đỉnh thị trường thu trọn tiền mặt về tài khoản",
  "Cải tạo nhà cũ nát thành căn hộ dịch vụ cao cấp nâng giá trị gấp đôi",
  "Con cái được học tập tại trường quốc tế ngay trong khuôn viên nội khu",
  "Sở hữu căn biệt thự view sông đắt giá khẳng định vị thế thành đạt",
  "Tạo dựng được cộng đồng cư dân văn minh tri thức và thân thiện",
  "Tiết kiệm được hàng trăm triệu đồng chi phí cải tạo nhờ tự lên kế hoạch",
  "Đạt tự do tài chính nhờ sở hữu chuỗi bất động sản cho thuê dòng tiền",
  "Mua được bất động sản phát mãi giá rẻ hơn 20 phần trăm so với thị trường",
  "Không gian sống tiện nghi hiện đại giúp tái tạo năng lượng mỗi ngày",
  "Bố mẹ dưỡng già an yên trong ngôi nhà vườn ngập tràn hoa lá",
  "Được bồi thường thỏa đáng và nhận suất đất tái định cư vị trí đắc địa",
  "Thành công chuyển đổi mục đích sử dụng đất nông nghiệp lên đất ở",
  "Mở rộng mặt bằng kinh doanh thuận lợi mang lại lợi nhuận vượt bậc",
  "Nhận trọn bộ nội thất cao cấp tặng kèm từ chương trình tri ân chủ đầu tư",
  "Tài sản nhân đôi giá trị sau khi dự án cầu vượt kết nối hoàn thành",
  "Tránh được bẫy lừa đảo bất động sản nhờ trang bị kiến thức pháp lý vững vàng",
  "Thanh toán dứt điểm toàn bộ khoản nợ vay ngân hàng trước hạn 3 năm",
  "Tận hưởng những ngày cuối tuần thảnh thơi bên gia đình tại căn nhà vườn",
  "Nâng tầm phong cách sống đẳng cấp với đầy đủ tiện ích chuẩn 5 sao",
  "Ký kết hợp đồng thuê dài hạn 5 năm với đối tác doanh nghiệp nước ngoài",
  "Tự tin đàm phán thành công mức giá tốt nhất trong mọi thương vụ",
  "Trở thành nhà đầu tư có uy tín và tiếng nói trong cộng đồng địa ốc",
  "Bảo toàn giá trị tài sản vượt qua giai đoạn lạm phát kinh tế an toàn",
  "Có được nguồn thu nhập thụ động bền vững an tâm tận hưởng cuộc sống",
  "Ngôi nhà tràn ngập ánh sáng tự nhiên giúp tiết kiệm tối đa điện năng",
  "Được ban quản lý tòa nhà hỗ trợ nhiệt tình giải quyết mọi vướng mắc",
  "Gia tăng giá trị tài sản gấp ba lần sau một chu kỳ đầu tư dài hạn",
  "Đón đầu làn sóng tăng giá mạnh mẽ khi khu công nghiệp đi vào hoạt động",
  "Giải quyết dứt điểm tranh chấp đất đai bảo vệ quyền lợi hợp pháp",
  "Sở hữu không gian làm việc tại nhà yên tĩnh sáng tạo và hiệu quả",
  "Hệ thống an ninh 24/7 mang lại sự an tâm tuyệt đối khi vắng nhà",
  "Chiết khấu trực tiếp 8 phần trăm vào giá bán nhờ thanh toán sớm",
  "Nhận chứng chỉ công trình xanh tiết kiệm năng lượng và thân thiện môi trường",
  "Xây dựng được danh mục đầu tư bất động sản đa dạng và an toàn",
  "Tạo dựng chốn đi về ấm áp gắn kết mọi thành viên trong gia đình",
  "Mặt bằng shophouse luôn có khách xếp hàng chờ thuê lại giá cao",
  "Hoàn thành mục tiêu mua nhà trước tuổi 30 của hai vợ chồng",
  "Được cấp giấy phép xây dựng thuận lợi không gặp bất kỳ trở ngại nào",
  "Khu nghỉ dưỡng luôn đạt công suất phòng trên 85 phần trăm quanh năm",
  "Bảo vệ gia đình khỏi ô nhiễm khói bụi nhờ khuôn viên cây xanh dày đặc",
  "Nhận được sự tin yêu và kính trọng từ bà con lối xóm xung quanh",
  "Đầu tư đúng phân khúc mang lại thanh khoản cao trong mọi thời điểm",
  "Căn nhà đón hướng gió mát mẻ quanh năm không cần bật điều hòa",
  "Nhanh chóng tìm được người mua lại với mức giá chênh lệch kỳ vọng",
  "Trang bị đầy đủ hệ thống phòng cháy chữa cháy đảm bảo an toàn tuyệt đối",
  "Có thêm nhiều người bạn láng giềng tốt bụng luôn sẵn sàng giúp đỡ",
  "Tài chính gia đình vững vàng tạo bước đệm cho các dự án kinh doanh tiếp theo",
  "Hạ tầng giao thông hoàn thiện giúp rút ngắn một nửa thời gian đi làm",
  "Trở thành tấm gương khởi nghiệp thành công truyền cảm hứng cho người trẻ",
  "Gia tăng giá trị bất động sản nhờ bổ sung thêm các tiện ích thông minh",
  "Tận hưởng bầu không khí trong lành giúp phục hồi sức khỏe nhanh chóng",
  "Giải phóng hoàn toàn áp lực tài chính sau khi tái cơ cấu lại danh mục tài sản",
  "Được cộng đồng cư dân tín nhiệm bầu vào ban quản trị tòa nhà",
  "Có được tài sản thừa kế giá trị truyền lại cho các thế hệ mai sau",
  "Khách thuê giữ gìn nhà cửa sạch sẽ và thanh toán tiền đúng hạn",
  "Dự án hoàn thiện đúng cam kết chất lượng nâng tầm uy tín nhà thầu",
  "Thu hút lượng khách du lịch đông đảo đến trải nghiệm dịch vụ nghỉ dưỡng",
  "Tiết kiệm hàng chục triệu đồng tiền điện nhờ thiết kế thông gió tự nhiên",
  "Môi trường sống lý tưởng giúp con cái phát triển toàn diện thể chất và tinh thần",
  "Nhận được nhiều lời khen ngợi từ bạn bè người thân khi đến thăm nhà mới",
  "Bảo vệ tài sản an toàn tuyệt đối trước mọi biến động phức tạp của thị trường",
  "Thực hiện trọn vẹn lời hứa xây nhà báo hiếu cho đấng sinh thành",
  "Hệ thống thoát nước hoàn hảo không bao giờ lo ngập úng mùa mưa bão",
  "Được ngân hàng nâng hạn mức tín dụng nhờ sở hữu nhiều bất động sản sạch",
  "Cộng đồng cư dân tổ chức nhiều hoạt động gắn kết văn minh ý nghĩa",
  "Khai thác kinh doanh cà phê sân vườn thành công thu hút đông đảo giới trẻ",
  "An tâm tuyệt đối về chất lượng xây dựng kiên cố vững chãi của ngôi nhà",
  "Tự do sáng tạo trang trí không gian sống theo phong cách riêng độc đáo",
  "Giá trị bất động sản tăng trưởng đều đặn 15 đến 20 phần trăm mỗi năm",
  "Có chốn bình yên thư thái để trở về sau những giờ làm việc căng thẳng",
  "Sở hữu mảnh đất sinh thái trù phú cung cấp thực phẩm sạch cho gia đình",
  "Nhận được sự hỗ trợ tài chính kịp thời từ người thân để chốt giao dịch",
  "Trải nghiệm trọn vẹn các tiện ích thể thao hồ bơi phòng gym ngay thềm nhà",
  "Hoàn thành xuất sắc chỉ tiêu doanh số năm được công ty vinh danh khen thưởng",
  "Tìm được người thuê nhà lâu dài có trách nhiệm gìn giữ tài sản",
  "Đầu tư thắng lợi giúp hiện thực hóa các ước mơ ấp ủ bấy lâu nay",
  "Khẳng định bản lĩnh và tầm nhìn chiến lược sáng suốt trong đầu tư nhà đất"
];

// 2. OTO (Ô tô) - 100 per field
const oto_boicanh = [
  "Showroom ô tô chính hãng 3S hiện đại khang trang",
  "Xưởng chăm sóc xe detailing chuyên nghiệp với phòng phủ ceramic",
  "Bãi xe ô tô đã qua sử dụng uy tín quy mô hàng trăm chiếc",
  "Cung đường ven biển lộng gió cát trắng nắng vàng ngập tràn",
  "Trung tâm đăng kiểm xe cơ giới đông đúc phương tiện xếp hàng",
  "Trạm sạc xe điện thông minh công suất cao bên đường cao tốc",
  "Xưởng dịch vụ bảo hành bảo dưỡng chính hãng giờ cao điểm",
  "Cung đường đèo dốc quanh co Tây Bắc đầy thử thách",
  "Tuyến đường ngập nước mùa mưa bão tại trung tâm thành phố",
  "Trạm dừng nghỉ cao tốc hiện đại rộng rãi thoáng mát",
  "Bãi biển cho phép lái xe hai cầu thử nghiệm sức kéo",
  "Trung tâm đào tạo lái xe và thi sát hạch sa hình",
  "Gara chuyên độ xe thể thao và nâng cấp âm thanh ánh sáng",
  "Bãi đỗ xe trung tâm thương mại thông minh nhiều tầng",
  "Tuyến phố đi bộ đông đúc xe cộ giờ tan tầm",
  "Cung đường offroad đồi cát lầy lội thử thách bản lĩnh",
  "Trạm rửa xe tự động không chạm công nghệ hiện đại",
  "Khu đô thị sinh thái với những cung đường rợp bóng cây",
  "Sân bay quốc tế đón tiếp đối tác bằng xe sang",
  "Cầu vượt biển dài nhất khu vực ngắm hoàng hôn",
  "Tuyến đường cao tốc 6 làn xe vận tốc tối đa 120km/h",
  "Xưởng phục hồi thân vỏ và đồng sơn xe sau va chạm",
  "Khu cắm trại ven hồ thiên nhiên cuối tuần của gia đình",
  "Phòng trưng bày siêu xe nhập khẩu phiên bản giới hạn",
  "Cửa hàng phụ kiện đồ chơi ô tô cao cấp phong phú",
  "Cung đường ven hồ Tây lãng mạn trong sương sớm",
  "Trạm dừng chân ngắm cảnh trên đỉnh đèo Hải Vân",
  "Bãi tập drift xe thể thao chuyên nghiệp an toàn",
  "Trung tâm cứu hộ giao thông 24/7 sẵn sàng ứng trực",
  "Hội chợ triển lãm ô tô quốc tế quy tụ nhiều thương hiệu",
  "Hầm chui nút giao thông hiện đại kết nối đô thị",
  "Cung đường hoa dã quỳ nở rộ hai bên sườn núi",
  "Khu nghỉ dưỡng sinh thái vùng núi có đường dốc cao",
  "Trạm bảo dưỡng lốp ô tô chuyên nghiệp cân mâm bấm chì",
  "Bãi giữ xe sân bay tấp nập phương tiện đưa đón",
  "Đường ven sông Sài Gòn rực rỡ ánh đèn đêm",
  "Cung đường đồi chè xanh mướt ngát hương vùng cao nguyên",
  "Xưởng dán phim cách nhiệt và dán decal đổi màu xe",
  "Khu chợ xe cũ nhộn nhịp kẻ mua người bán trao đổi",
  "Tuyến đường nông thôn mới rải nhựa khang trang sạch đẹp",
  "Trạm kiểm tra khí thải ô tô theo tiêu chuẩn mới",
  "Sân golf cao cấp nơi các dòng xe sang hội tụ",
  "Cung đường chạy thử xe chuyên biệt của nhà máy sản xuất",
  "Khu đô thị thông minh với làn đường riêng cho xe tự hành",
  "Bãi đỗ xe tầng hầm chung cư cao cấp trang bị trạm sạc",
  "Cung đường tuần tra biên giới hùng vĩ và hiểm trở",
  "Trạm cân tải trọng xe lưu động trên quốc lộ",
  "Xưởng phục chế xe cổ mang đậm dấu ấn thời gian",
  "Khu cắm trại glamping ven rừng thông mát mẻ",
  "Đại lộ trung tâm rực rỡ cờ hoa ngày lễ lớn",
  "Cung đường đất đỏ bazan Tây Nguyên mùa mưa trơn trượt",
  "Trạm dịch vụ sửa chữa lưu động trên đường cao tốc",
  "Cầu dây văng hiện đại lung linh ánh đèn led nghệ thuật",
  "Bãi thử nghiệm tính năng hỗ trợ lái thông minh ADAS",
  "Khu chợ đêm ẩm thực tấp nập người qua lại",
  "Tuyến đường đèo dốc sương mù dày đặc che khuất tầm nhìn",
  "Cửa khẩu quốc tế thông thương hàng hóa nhộn nhịp",
  "Xưởng nâng cấp ánh sáng bi led laser siêu sáng cho xe",
  "Khu công nghiệp tập trung nhiều xe đưa đón chuyên gia",
  "Bến phà vượt sông lớn tấp nập xe cộ nối đuôi nhau",
  "Cung đường sa mạc cát mênh mông nắng gió miền duyên hải",
  "Trạm tiếp nhiên liệu sinh học thân thiện với môi trường",
  "Khu du lịch suối khoáng nóng trên sườn núi cao",
  "Xưởng độ nẹp bodykit và mâm đúc hợp kim phong cách",
  "Tuyến đường tránh thành phố thông thoáng không kẹt xe",
  "Cung đường ruộng bậc thang uốn lượn mùa lúa chín",
  "Bãi gửi xe bệnh viện lớn luôn trong tình trạng kín chỗ",
  "Khu tái định cư với mạng lưới đường bàn cờ rộng rãi",
  "Trạm sạc nhanh 15 phút đầy 80 phần trăm pin xe điện",
  "Cung đường ven vách đá một bên là núi một bên là biển",
  "Xưởng may ghế da ô tô cao cấp theo yêu cầu cá nhân hóa",
  "Hội trường lễ ra mắt mẫu xe SUV thế hệ mới",
  "Tuyến phố cổ kính với những con ngõ nhỏ đặc trưng",
  "Trạm nghỉ chân ven suối trong lành mát rượi",
  "Khu trải nghiệm lái xe mô phỏng thực tế ảo 3D",
  "Đường chạy thử nghiệm phanh khẩn cấp trên mặt đường trơn",
  "Bãi xe cảng biển tiếp nhận hàng ngàn ô tô nhập khẩu",
  "Cung đường rừng nguyên sinh không khí trong lành tinh khiết",
  "Xưởng cách âm chống ồn toàn diện cho khoang cabin",
  "Khu dân cư ven biển đón gió mặn quanh năm",
  "Trạm dừng kỹ thuật kiểm tra áp suất lốp tự động",
  "Tuyến đường cao tốc trên cao xuyên tâm đô thị",
  "Cung đường chinh phục cột cờ vùng cực Bắc Tổ quốc",
  "Xưởng độ hệ thống treo khí nén nâng hạ gầm êm ái",
  "Khu nghỉ dưỡng ven hồ nhân tạo phẳng lặng như gương",
  "Bãi tập sa hình sát hạch lái xe hạng B2 và C",
  "Tuyến phố ẩm thực sầm uất sáng đèn thâu đêm",
  "Trạm cứu hộ ắc quy và vá lốp lưu động cấp tốc",
  "Cung đường hoa ban nở trắng muốt sườn núi Tây Bắc",
  "Xưởng sơn sấy công nghệ cao tiêu chuẩn chính hãng",
  "Khu phức hợp dịch vụ xe hơi all in one tiện ích",
  "Tuyến đường đèo dốc có nhiều khúc cua tay áo",
  "Trạm dừng chân ngắm bình minh trên đỉnh núi cao",
  "Bãi đỗ xe thông minh tự động xếp xe bằng robot",
  "Cung đường ven đầm phá mênh mông nước biếc",
  "Xưởng lắp đặt màn hình android và camera 360 độ",
  "Khu đô thị sinh thái bên bờ sông xanh mát",
  "Tuyến đường huyết mạch nối liền sân bay với trung tâm",
  "Trạm kiểm định an toàn kỹ thuật phương tiện cơ giới",
  "Showroom xe đã qua sử dụng bảo hành chính hãng toàn quốc"
];

const oto_nhanvat = [
  "Tư vấn bán hàng ô tô tận tâm am hiểu kỹ thuật sâu sắc",
  "Vợ chồng trẻ mua chiếc ô tô gia đình đầu tiên che mưa nắng",
  "Doanh nhân thành đạt tìm kiếm xe sang khẳng định đẳng cấp",
  "Bác tài xế xe công nghệ tính toán chi phí vận hành tối ưu",
  "Người đam mê phượt thích xe hai cầu gầm cao vượt mọi địa hình",
  "Thợ kỹ thuật detailing tỉ mỉ chăm chút từng chi tiết lớp sơn",
  "Bác thợ máy lão thành giàu kinh nghiệm bắt bệnh động cơ",
  "Nữ nhân viên văn phòng tìm mua xe hatchback nhỏ gọn đi phố",
  "Gia đình nhiều thế hệ lựa chọn mẫu xe MPV 7 chỗ rộng rãi",
  "Chuyên gia thẩm định xe cũ kiểm tra keo chỉ và động cơ",
  "Chủ doanh nghiệp vận tải đầu tư đội xe thương mại mới",
  "Chàng trai trẻ yêu thích độ xe phong cách thể thao cá tính",
  "Cán bộ ngân hàng hỗ trợ gói vay mua xe trả góp lãi suất thấp",
  "Người mới nhận bằng lái còn lo lắng khi lái xe vào giờ cao điểm",
  "YouTuber chuyên lái thử và đánh giá xe ô tô chân thực",
  "Chủ gara sửa chữa ô tô uy tín luôn đặt chữ tâm lên đầu",
  "Khách hàng khó tính yêu cầu kiểm tra kỹ từng tính năng an toàn",
  "Bác tài lái xe đường dài chia sẻ kinh nghiệm xử lý tình huống",
  "Người phụ nữ hiện đại tự tin cầm lái chiếc SUV mạnh mẽ",
  "Chuyên viên bảo hiểm tư vấn gói bảo hiểm thân vỏ toàn diện",
  "Người yêu công nghệ háo hức chuyển đổi sang dùng xe điện thông minh",
  "Chủ trang trại mua xe bán tải phục vụ công việc chuyên chở",
  "Trưởng phòng dịch vụ tận tình giải đáp thắc mắc bảo hành của khách",
  "Khách hàng mua xe cũ lần đầu lo lắng nguy cơ xe từng bị ngập nước",
  "Chuyên gia âm thanh xe hơi thiết kế hệ thống loa Hi-End đỉnh cao",
  "Người sưu tầm xe cổ dành nhiều tâm huyết phục chế từng chi tiết",
  "Cặp đôi mới cưới cùng nhau chọn màu xe hợp phong thủy bản mệnh",
  "Chủ xưởng dán decal tạo ra những mẫu tem xe độc đáo ấn tượng",
  "Bác sĩ chọn mẫu xe có hệ thống lọc không khí và ghế êm ái",
  "Nhân viên cứu hộ giao thông không ngại đêm hôm mưa gió hỗ trợ tài xế",
  "Chuyên viên đăng ký xe hỗ trợ bấm biển số và đăng kiểm trọn gói",
  "Người lái xe kỳ cựu luôn tuân thủ nguyên tắc giữ khoảng cách an toàn",
  "Thầy giáo dạy lái xe tận tâm hướng dẫn từng thao tác sa hình",
  "Chủ chuỗi cửa hàng bán lẻ mua xe van chở hàng tiện lợi trong phố",
  "Nhà sáng lập công ty công nghệ trải nghiệm tính năng tự hành",
  "Khách hàng trung niên ưu tiên xe có khung gầm đầm chắc cách âm tốt",
  "Kỹ thuật viên điện lạnh xử lý triệt để mùi hôi trong hệ thống điều hòa",
  "Người nông dân trúng mùa đổi chiếc xe hơi đời mới tặng vợ con",
  "Chuyên viên kiểm định khí thải giải thích tiêu chuẩn bảo vệ môi trường",
  "Chàng kỹ sư cơ khí yêu thích tìm hiểu cấu tạo khối động cơ hybrid",
  "Người nội trợ chuộng xe có cốp rộng rãi chứa được nhiều đồ mua sắm",
  "Chủ khách sạn mua xe limousine phục vụ khách VIP đưa đón sân bay",
  "Nhiếp ảnh gia dùng xe bán tải cắm trại chụp ảnh phong cảnh thiên nhiên",
  "Người mua xe cân nhắc kỹ mức tiêu hao nhiên liệu trên 100 kilomet",
  "Thợ may nội thất da ô tô khéo léo may từng đường chỉ sắc sảo",
  "Vận động viên thể thao chọn xe gầm cao chở theo xe đạp và đồ dã ngoại",
  "Chủ đội xe cứu thương tư nhân bảo dưỡng xe luôn sẵn sàng cấp cứu",
  "Khách hàng trẻ tuổi chuộng xe có kết nối Apple CarPlay không dây",
  "Chuyên viên tư vấn phụ kiện khuyên lắp camera hành trình chất lượng",
  "Người lái xe đường đèo dốc luôn kiểm tra phanh và áp suất lốp trước chuyến đi",
  "Bác bảo vệ bãi xe nhiệt tình hướng dẫn khách ghép xe vào chuồng",
  "Nhà đầu tư cho thuê xe tự lái mở rộng quy mô đội xe đời mới",
  "Kỹ sư lập trình phần mềm ô tô cập nhật firmware qua mạng không dây",
  "Người mua xe lần 2 chú trọng đến giá trị bán lại sau 5 năm sử dụng",
  "Chủ xưởng độ đèn nâng cấp ánh sáng giúp tài xế quan sát an toàn ban đêm",
  "Chị tiểu thương tích cóp mua chiếc xe che mưa nắng cho các con đi học",
  "Chuyên gia an toàn giao thông chia sẻ kỹ năng thoát hiểm khi xe ngập",
  "Người lái xe điềm tĩnh luôn nhường đường cho người đi bộ qua đường",
  "Thợ cân chỉnh góc đặt bánh xe bằng công nghệ laser 3D chính xác",
  "Doanh nhân trẻ tự thưởng cho mình chiếc xe thể thao nhân dịp sinh nhật",
  "Bà mẹ bỉm sữa chọn xe có móc gắn ghế trẻ em chuẩn ISOFIX an toàn",
  "Chủ xưởng rửa xe không chạm luôn nâng cao chất lượng phục vụ khách",
  "Người mua xe thanh toán dứt điểm 100 phần trăm tiền mặt tự tin nhận xe",
  "Chuyên viên chăm sóc khách hàng gọi điện nhắc lịch bảo dưỡng định kỳ",
  "Thợ dán phim cách nhiệt cẩn thận không để lại bọt khí trên kính lái",
  "Khách hàng đam mê âm nhạc yêu cầu nâng cấp dàn loa hàng hiệu Subwoofer",
  "Người cao tuổi thích mẫu xe có tầm nhìn thoáng và bảng điều khiển trực quan",
  "Chủ xe cẩn thận luôn rửa xe sạch sẽ sau mỗi chuyến đi xa",
  "Nhân viên trạm xăng dầu phục vụ văn minh và lau kính xe miễn phí cho khách",
  "Chuyên gia lốp xe hướng dẫn cách nhận biết gai lốp mòn cần thay thế",
  "Người yêu thiên nhiên chuộng dòng xe thuần điện không phát thải khói bụi",
  "Cán bộ hưu trí dùng xe đưa đón các cháu đi học mỗi ngày",
  "Chủ xe bán tải tham gia câu lạc bộ cứu hộ bão lũ vùng sâu vùng xa",
  "Thợ đồng sơn pha màu sơn trùng khớp 100 phần trăm với màu gốc",
  "Người mua xe kỹ tính yêu cầu chạy thử trên nhiều điều kiện mặt đường",
  "Chuyên viên cứu hộ pin xe điện trang bị trạm sạc lưu động cấp tốc",
  "Người lái xe luôn thắt dây an toàn cho bản thân và người ngồi cùng",
  "Chủ doanh nghiệp du lịch đầu tư dàn xe 16 chỗ phục vụ tour lữ hành",
  "Kỹ thuật viên kiểm tra ắc quy và hệ thống sạc máy phát điện xe",
  "Người chạy xe dịch vụ biết cách lái xe êm ái làm hài lòng mọi hành khách",
  "Chuyên viên thẩm định giá xe cũ đưa ra mức định giá hợp lý cho cả đôi bên",
  "Thợ dán PPF bảo vệ sơn xe chống trầy xước từ đá văng trên đường",
  "Khách hàng ở tỉnh xa lặn lội đến showroom lớn để chọn màu xe ưng ý",
  "Người chủ xe tự tay thay lốp dự phòng thành thạo khi gặp sự cố giữa đường",
  "Chuyên gia kỹ thuật hướng dẫn khách hàng sử dụng tính năng giữ làn đường",
  "Bác tài xe tải dày dạn kinh nghiệm vượt đèo an toàn trong sương mù",
  "Người mua xe thông thái tận dụng các đợt ưu đãi 100 phần trăm lệ phí trước bạ",
  "Chủ tiệm sửa xe máy mở rộng nâng cấp xưởng dịch vụ chăm sóc ô tô",
  "Người trẻ khởi nghiệp chọn chiếc xe bán tải vừa chở hàng vừa đi chơi",
  "Kỹ sư thiết kế khí động học tối ưu hóa hình dáng xe giảm lực cản gió",
  "Khách hàng trung thành luôn bảo dưỡng xe đúng số kilomet quy định",
  "Chuyên viên tư vấn tài chính hỗ trợ hồ sơ vay mua xe duyệt trong 2 giờ",
  "Chủ xe tự hào khoe chiếc xe sạch bóng sau khi tự tay rửa xe cuối tuần",
  "Người lái xe ban đêm luôn hạ đèn pha về cos khi gặp xe đi ngược chiều",
  "Thợ phục hồi ghế da xóa sạch các vết rạn nứt trả lại vẻ đẹp ban đầu",
  "Người mua xe ưu tiên chọn đại lý có dịch vụ hậu mãi chu đáo và phụ tùng sẵn",
  "Chuyên gia khí thải tư vấn dung dịch xử lý khí thải động cơ diesel AdBlue",
  "Người sử dụng xe điện chia sẻ kinh nghiệm tối ưu hóa quãng đường di chuyển",
  "Bác tài xế luôn kiểm tra nước làm mát và dầu máy trước mỗi chuyến hành trình",
  "Người mua xe hài lòng với quyết định nâng cấp lên dòng xe an toàn cao cấp"
];

const oto_hanhdong = [
  "Trực tiếp cầm lái thử nghiệm khả năng tăng tốc và độ nhạy chân ga",
  "Kiểm tra kỹ lưỡng từng mối hàn keo chỉ xung quanh nắp capo và cốp xe",
  "So sánh bảng chi phí lăn bánh và mức ưu đãi giữa ba đại lý chính hãng",
  "Nâng gầm xe lên cầu nâng để kiểm tra hệ thống treo và thước lái",
  "Dùng máy quét lỗi chuyên dụng đọc toàn bộ mã lỗi từ hộp đen ECU",
  "Kiểm tra lịch sử bảo hành bảo dưỡng định kỳ trên hệ thống đại lý toàn quốc",
  "Đo độ dày lớp sơn bằng máy đo chuyên dụng phát hiện khu vực từng bắn sơn",
  "Chạy thử xe qua gờ giảm tốc để lắng nghe tiếng kêu lục cục ở gầm xe",
  "Đàm phán xin thêm gói phụ kiện dán phim cách nhiệt và thảm lót sàn cao cấp",
  "Thực hiện thủ tục đăng ký bấm biển số xe tại phòng cảnh sát giao thông",
  "Đưa xe vào trung tâm đăng kiểm kiểm tra phanh và độ chụm bánh xe",
  "Lắp đặt hệ thống camera hành trình ghi hình trước sau tích hợp cảnh báo giao thông",
  "Phủ lớp ceramic bóng bẩy bảo vệ bề mặt sơn xe khỏi tác động tia UV",
  "Dán phim cách nhiệt chất lượng cao loại bỏ 99 phần trăm tia hồng ngoại",
  "Kiểm tra mức độ tiêu hao dầu nhớt và màu sắc của dầu hộp số tự động",
  "Thử nghiệm tính năng phanh tự động khẩn cấp khi phát hiện chướng ngại vật",
  "Đo áp suất 4 lốp xe và bơm lốp đúng chuẩn khuyến cáo của nhà sản xuất",
  "Vệ sinh khoang động cơ bằng hơi nước nóng chuyên nghiệp không lo chập điện",
  "Khử mùi nội thất và diệt khuẩn điều hòa bằng máy tạo ozone tự nhiên",
  "Thay mới toàn bộ dàn lốp Michelin êm ái bám đường tốt trong trời mưa",
  "Nâng cấp hệ thống đèn bi led tăng cường độ chiếu sáng an toàn ban đêm",
  "Lắp đặt cảm biến áp suất lốp tích hợp hiển thị trực tiếp lên màn hình xe",
  "Thực hiện cân bằng động 4 bánh xe và bấm chì triệt tiêu rung lắc vô lăng",
  "Căn chỉnh thước lái và góc đặt bánh xe bằng hệ thống 3D chuyên dụng",
  "Lắp thảm lót sàn tràn viền chất liệu da cao cấp dễ lau chùi vệ sinh",
  "Bảo dưỡng hệ thống phanh tháo vệ sinh cùm phanh và tra mỡ chịu nhiệt",
  "Thay lọc gió động cơ và lọc gió điều hòa định kỳ sau mỗi 10000 kilomet",
  "Thay mới dung dịch nước làm mát chống sôi và chống ăn mòn két nước",
  "Lập hồ sơ vay vốn mua xe ô tô trả góp tại ngân hàng liên kết ưu đãi",
  "Ký hợp đồng mua bán xe và bàn giao giấy tờ gốc có công chứng đầy đủ",
  "Cài đặt ứng dụng thông minh trên điện thoại kết nối điều khiển xe từ xa",
  "Bật tính năng ga tự động thích ứng Adaptive Cruise Control trên cao tốc",
  "Kiểm tra tình trạng hao mòn của má phanh và đĩa phanh trước sau",
  "Đổ đầy bình nhiên liệu và thêm phụ gia vệ sinh kim phun buồng đốt",
  "Kiểm tra hệ thống túi khí và dây đai an toàn đa điểm trong khoang lái",
  "Tự tay thay cần gạt mưa mới loại bỏ hoàn toàn vết mờ trên kính lái",
  "Thử nghiệm tính năng cảnh báo điểm mù trên gương chiếu hậu ngoài",
  "Kiểm tra khả năng lội nước của xe qua đoạn đường ngập nhẹ an toàn",
  "Thực hiện thao tác ghép xe song song vào chuồng hẹp bằng camera 360",
  "Dán màng bảo vệ sơn PPF cho các chi tiết dễ trầy xước như hõm cửa và gương",
  "Phục hồi độ sáng bóng cho chóa đèn pha ố vàng bằng dung dịch chuyên dụng",
  "Thay dầu trợ lực lái và kiểm tra độ rơ của vô lăng khi đánh hết lái",
  "Đọc kỹ sách hướng dẫn sử dụng xe để nắm rõ các tính năng an toàn hiện đại",
  "Chuyển chế độ lái sang Sport để trải nghiệm cảm giác dính lưng phấn khích",
  "Kiểm tra bình ắc quy bằng máy đo điện áp và dòng khởi động nguội CCA",
  "Lắp giá nóc chở đồ và giá treo xe đạp phục vụ chuyến đi dã ngoại",
  "Đưa xe đi bảo dưỡng mốc lớn 40000 kilomet thay toàn bộ các loại dung dịch",
  "Thương lượng mức giá bán lại tốt nhất cho chiếc xe cũ tại salon uy tín",
  "Cài đặt giới hạn tốc độ xe khi cho mượn hoặc khi lưu thông trong phố",
  "Kiểm tra hoạt động của bơm xăng và hệ thống tuần hoàn khí thải EGR",
  "Lắp đặt hệ thống định vị GPS quản lý xe từ xa chống trộm hiệu quả",
  "Xử lý vết trầy xước sơn nhẹ bằng phương pháp đánh bóng cana chuyên nghiệp",
  "Thay gioăng cao su cánh cửa giúp tăng cường khả năng cách âm chống ồn",
  "Trải nghiệm tính năng hỗ trợ giữ làn đường và tự động đánh lái khẩn cấp",
  "Kiểm tra độ cân bằng của hệ thống giảm xóc trên máy đo dao động",
  "Lắp đặt bệ bước chân tự động thụt thò cho dòng xe gầm cao tiện lợi",
  "Vệ sinh cổ hút và bướm ga giúp động cơ hoạt động mượt mà tiết kiệm nhiên liệu",
  "Thay nắp két nước mới đảm bảo áp suất chuẩn cho hệ thống làm mát",
  "Ký hợp đồng bảo hiểm vật chất xe với điều khoản bảo hiểm ngập nước thủy kích",
  "Kiểm tra thời hạn bảo hành pin và dung lượng khả dụng của xe điện",
  "Thử nghiệm tính năng sưởi ghế và làm mát ghế trong điều kiện thời tiết khắc nghiệt",
  "Kiểm tra tình trạng rò rỉ dầu máy dưới gầm động cơ sau chuyến đi dài",
  "Lắp đặt rèm che nắng nam châm theo form kính từng cánh cửa xe",
  "Thay bugi Iridium mới giúp đánh lửa mạnh và đốt cháy nhiên liệu triệt để",
  "Xúc rửa két nước làm mát loại bỏ cặn bẩn bám lâu ngày trong đường ống",
  "Đăng ký tài khoản thu phí không dừng ETC và nạp sẵn tiền vào tài khoản",
  "Kiểm tra lốp dự phòng và bộ dụng cụ con đội kích xe sẵn sàng trên xe",
  "Vệ sinh cảm biến lưu lượng khí nạp MAF giúp xe không bị giật cục khi tăng ga",
  "Thay dầu hộp số tuần hoàn bằng máy tự động loại bỏ cặn bẩn hoàn toàn",
  "Lắp đặt bơm lốp mini điện tử và bộ vá lốp khẩn cấp trong cốp xe",
  "Kiểm tra hệ thống đèn chiếu sáng ban ngày DRL và đèn xi nhan tuần tự",
  "Đặt lịch hẹn dịch vụ bảo dưỡng trước qua ứng dụng di động của hãng",
  "Kiểm tra độ chụm và góc camber bánh xe giúp lốp mòn đều tăng tuổi thọ",
  "Bọc vô lăng bằng da Nappa thật tạo cảm giác cầm nắm chắc chắn đầm tay",
  "Thực hiện khử tĩnh điện cho thân xe giảm bám bụi khi di chuyển đường dài",
  "Tải bản đồ dẫn đường ngoại tuyến mới nhất cập nhật biển báo tốc độ",
  "Kiểm tra hệ thống điều hòa tự động hai vùng độc lập làm lạnh nhanh sâu",
  "Thay má phanh gốm cao cấp giảm thiểu bụi than bám vào la zăng",
  "Nâng cấp dàn âm thanh 8 loa vòm mang lại không gian âm nhạc sống động",
  "Lắp đặt thanh giằng khoang động cơ Strut Bar giúp xe ôm cua vững chãi hơn",
  "Kiểm tra hoạt động của mô tơ gạt mưa và bơm nước rửa kính trước sau",
  "Khám phá các tính năng ẩn trên xe thông qua phần mềm kích hoạt chuyên sâu",
  "Thay toàn bộ ốc tắc kê bánh xe bằng hợp kim titan siêu nhẹ chống gỉ sét",
  "Tập thói quen kiểm tra xung quanh xe trước khi bước lên ghế lái nổ máy",
  "Tháo vệ sinh bình xăng và thay lưới lọc xăng định kỳ sau 80000 kilomet",
  "Kiểm tra hệ thống chống bó cứng phanh ABS khi đạp phanh gấp trên đường trơn",
  "Lắp đặt sạc không dây chuẩn Qi tiện lợi trên bệ tỳ tay trung tâm",
  "Kiểm tra độ kín khít của cửa sổ trời chống dột nước khi trời mưa to",
  "Thương lượng giữ lại biển số đẹp theo quy định định danh biển số mới",
  "Rửa sạch gầm xe sau khi đi qua vùng đất cát hoặc vùng ngập nước mặn",
  "Kiểm tra tình trạng cao su chân máy và chân hộp số triệt tiêu độ rung",
  "Lắp đặt camera tiến cập lề giúp căn chỉnh bánh trước dễ dàng không cạ lề",
  "Thay dầu phanh DOT 4 mới ngăn ngừa hiện tượng mất phanh do sôi dầu",
  "Kiểm tra hoạt động của gương chiếu hậu gập điện tự động khi khóa cửa",
  "Dán cách âm hốc lốp bằng vật liệu chống rung và tiêu âm chuyên dụng",
  "Kiểm tra độ chùng của dây curoa tổng và thay mới nếu phát hiện vết nứt",
  "Vệ sinh đường ống dẫn gió máy lạnh bằng bình xịt bọt tuyết chuyên sâu",
  "Thử nghiệm chức năng hỗ trợ đổ đèo tự động hãm tốc độ an toàn",
  "Gửi phản hồi đánh giá chất lượng dịch vụ sau khi nhận xe từ xưởng sửa chữa",
  "Chụp lại hình ảnh đồng hồ công tơ mét đối chiếu với số kilomet trên hợp đồng"
];

const oto_ketqua = [
  "Sở hữu chiếc xe ô tô ưng ý nâng tầm chất lượng cuộc sống cả gia đình",
  "Tự tin lái xe an toàn che mưa che nắng bảo vệ sức khỏe người thân",
  "Tiết kiệm 30 triệu đồng nhờ chọn đúng thời điểm hưởng ưu đãi trước bạ",
  "Mua được chiếc xe cũ chất lượng như mới nguyên bản không một lỗi nhỏ",
  "Nhận bàn giao xe mới bóng bẩy đúng dịp sum họp gia đình ngày Tết",
  "Bấm được biển số xe phong thủy đẹp mang lại may mắn trong công việc",
  "Xe vận hành êm ái đầm chắc tiết kiệm nhiên liệu chỉ 5 lít trên 100km",
  "Hoàn tất thủ tục sang tên đổi biển số nhanh gọn chỉ trong 3 ngày",
  "Bảo vệ bề mặt sơn xe luôn bóng bẩy như mới sau nhiều năm sử dụng",
  "Nội thất khoang lái luôn thơm tho sạch sẽ trong lành không mùi ẩm mốc",
  "Chuyến đi phượt xuyên Việt 3000 kilomet an toàn trọn vẹn đầy kỷ niệm đẹp",
  "Khoang cabin yên tĩnh tuyệt đối không còn tiếng ồn khó chịu từ gầm xe",
  "Hệ thống phanh tự động kịp thời ngăn chặn một vụ va chạm trên cao tốc",
  "Hồ sơ vay ngân hàng được phê duyệt nhanh chóng với lãi suất cố định 2 năm",
  "Động cơ hoạt động bền bỉ mượt mà đạt mốc 100000 kilomet không hỏng vặt",
  "Nâng tầm phong cách cá nhân và khẳng định uy tín với đối tác làm ăn",
  "Tự tin làm chủ tay lái vượt qua những cung đường đèo dốc hiểm trở",
  "Bán lại chiếc xe cũ với mức giá cao nhờ giữ gìn cẩn thận và bảo dưỡng đều",
  "Được đại lý hỗ trợ cứu hộ giao thông miễn phí kịp thời trong đêm",
  "Không gian nội thất rộng rãi mang lại sự thoải mái tối đa cho cả gia đình",
  "Hệ thống chiếu sáng mới giúp quan sát rõ ràng tầm nhìn xa trong đêm tối",
  "Hạn chế tối đa nguy cơ nổ lốp nhờ hệ thống cảm biến cảnh báo áp suất sớm",
  "Dàn âm thanh chất lượng cao mang lại những phút giây thư giãn tuyệt vời",
  "Lớp phim cách nhiệt giúp khoang xe luôn mát mẻ tiết kiệm điện điều hòa",
  "Tránh được rủi ro mua phải xe ngập nước thủy kích nhờ kiểm tra chuyên sâu",
  "Chuyến đi công tác xa thuận lợi giúp ký kết thành công hợp đồng lớn",
  "Tự tay chăm sóc chiếc xe sạch đẹp mang lại niềm vui và sự tự hào mỗi ngày",
  "Hệ thống an toàn chủ động hoạt động chính xác mang lại sự an tâm tuyệt đối",
  "Chi phí vận hành và bảo dưỡng hợp lý nằm trong khả năng tài chính dự kiến",
  "Được cộng đồng yêu xe đánh giá cao về bản độ xe thể thao tinh tế",
  "Gia đình gắn kết hơn qua những chuyến đi dã ngoại cắm trại cuối tuần",
  "Không còn nỗi ám ảnh kẹt xe dưới trời mưa gió hay khói bụi ô nhiễm",
  "Xử lý thành thạo sự cố xẹp lốp giữa đường mà không cần gọi cứu hộ",
  "Được cấp giấy chứng nhận đăng kiểm phương tiện an toàn đạt chuẩn lưu hành",
  "Chiếc xe điện vận hành êm ru thân thiện môi trường tiết kiệm chi phí sạc",
  "Tối ưu hóa thời gian di chuyển hàng ngày giúp nâng cao hiệu suất làm việc",
  "Nhận gói bảo hành mở rộng chính hãng 5 năm an tâm tuyệt đối trên mọi nẻo đường",
  "Hệ thống điều hòa hai vùng độc lập làm hài lòng mọi thành viên trên xe",
  "Khám phá thêm nhiều vùng đất mới hùng vĩ cùng người bạn đồng hành 4 bánh",
  "Chiếc xe bán tải phục vụ đắc lực công việc kinh doanh và chở hàng hóa",
  "Tránh được việc bị phạt nguội nhờ camera hành trình cảnh báo tốc độ chuẩn",
  "Lớp màng bảo vệ PPF giữ cho cụm đèn pha và cản trước không bị trầy xước",
  "Nâng cao kỹ năng lái xe chuyên nghiệp và xử lý tình huống giao thông bình tĩnh",
  "Nhận được sự phục vụ tận tình chu đáo từ đội ngũ cố vấn dịch vụ chính hãng",
  "Tài sản được bảo vệ toàn diện với gói bảo hiểm thân vỏ uy tín",
  "Được người thân và bạn bè chúc mừng trong ngày lễ nhận xe mới",
  "Khởi đầu hành trình kinh doanh dịch vụ vận tải thuận lợi sinh lời đều đặn",
  "Xe khởi động tức thì êm ái ngay cả trong thời tiết giá lạnh vùng cao",
  "Tận hưởng trọn vẹn tầm nhìn khoáng đạt qua cửa sổ trời toàn cảnh panorama",
  "Sở hữu chiếc xe phù hợp nhu cầu giúp cân bằng giữa công việc và gia đình",
  "Nâng cao vị thế và sự tự tin khi xuất hiện trong các sự kiện quan trọng",
  "Hệ thống lọc không khí ion âm bảo vệ hệ hô hấp của trẻ nhỏ trên xe",
  "Dễ dàng ghép xe vào điểm đỗ chật hẹp nhờ sự trợ giúp của camera 360 độ",
  "Hưởng trọn vẹn các chính sách hậu mãi và tích điểm dịch vụ thành viên VIP",
  "Cốp xe đóng mở rảnh tay thông minh tiện lợi khi xách nhiều đồ đạc",
  "Tiết kiệm thời gian qua trạm thu phí nhờ tài khoản ETC hoạt động mượt mà",
  "Tự do khám phá những cung đường ven biển tuyệt đẹp theo lịch trình riêng",
  "Động cơ hybrid kết hợp hoàn hảo mang lại khả năng tăng tốc tức thì",
  "Chiếc xe luôn trong tình trạng hoàn hảo sẵn sàng cho những chuyến đi bất ngờ",
  "Đạt giải thưởng trong cuộc thi xe đẹp do câu lạc bộ ô tô toàn quốc tổ chức",
  "Tự tin cầm lái trong mọi điều kiện thời tiết mưa to gió lớn đường trơn",
  "Bảo vệ an toàn tuyệt đối cho bé yêu với ghế ngồi chuyên dụng chuẩn ISOFIX",
  "Hoàn thành trọn vẹn mục tiêu mua ô tô tự thưởng cho bản thân sau nhiều nỗ lực",
  "Xe được định giá cao khi thế chấp ngân hàng để mở rộng vốn kinh doanh",
  "Cảm giác lái đầm chắc chân thật mang lại sự phấn khích sau mỗi cú nhấn ga",
  "Xóa tan hoàn toàn nỗi lo say xe của người thân nhờ khoang xe thoáng đãng",
  "Hệ thống sạc không dây giúp khoang lái luôn gọn gàng không vướng dây cáp",
  "Giữ vững phong độ vận hành mượt mà sau hàng chục vạn kilomet sử dụng",
  "Nhận được nhiều lời khen ngợi về màu xe độc đáo và phong cách sang trọng",
  "Tự hào là tấm gương truyền cảm hứng nỗ lực vươn lên cho con cái noi theo",
  "Làm chủ hoàn toàn các công nghệ hiện đại thông minh trang bị trên xe",
  "Tạo dựng hình ảnh chuyên nghiệp trong mắt đối tác và khách hàng lớn",
  "Chuyến hành trình về quê ăn Tết ấm áp an toàn trên chiếc xe riêng của gia đình",
  "Thoát khỏi vũng lầy lội dễ dàng nhờ hệ dẫn động 4 bánh toàn thời gian",
  "Tiết kiệm hàng chục triệu đồng tiền sửa chữa nhờ phát hiện lỗi sớm",
  "Hài lòng với quyết định đầu tư chiếc xe phục vụ nhu cầu đi lại thiết thực",
  "Được hỗ trợ thay thế phụ tùng chính hãng nhanh chóng trong vòng 24 giờ",
  "Bảo vệ các chi tiết nội thất nhựa và da không bị bạc màu dưới nắng gắt",
  "Tận hưởng không gian riêng tư trò chuyện thoải mái cùng gia đình trên xe",
  "Hệ thống ga tự động thích ứng giúp giảm mệt mỏi đáng kể khi lái xe đường dài",
  "Được cộng đồng mạng yêu thích qua video chia sẻ kinh nghiệm bảo dưỡng xe",
  "Chiếc xe luôn sáng bóng sạch sẽ tạo ấn tượng tốt với người đi cùng",
  "Chuyển số mượt mà không hề có cảm giác giật cục nhờ hộp số vô cấp hiện đại",
  "Đóng góp tích cực vào việc giảm phát thải khi sử dụng phương tiện xanh",
  "An tâm gửi gắm chiếc xe cho đội ngũ kỹ thuật viên tay nghề cao chăm sóc",
  "Cảm giác tự do tự tại khi có thể lên đường bất cứ lúc nào mình muốn",
  "Bảo tồn giá trị xe ở mức cao nhất sau nhiều năm gắn bó",
  "Tạo nên những kỉ niệm tuổi thơ đáng nhớ cho các con qua từng chuyến đi xa",
  "Xử lý dứt điểm các tiếng kêu lọc cọc mang lại không gian tĩnh lặng",
  "Được hưởng chính sách cứu hộ pin xe điện 24/7 hoàn toàn miễn phí",
  "Cân bằng hoàn hảo giữa tính năng thực dụng và thẩm mỹ tinh tế của xe",
  "Tự hào sở hữu chiếc xe do chính bàn tay và khối óc mình làm ra",
  "Hệ thống treo khí nén êm ái nuốt trọn mọi ổ gà trên đường mấp mô",
  "Nhận được sự tin tưởng tuyệt đối của người thân khi ngồi sau tay lái",
  "Khởi đầu một năm mới may mắn hanh thông bên cạnh chiếc xe yêu quý",
  "Tiết kiệm chi phí bảo trì nhờ tuân thủ nghiêm ngặt lịch bảo dưỡng định kỳ",
  "Trải nghiệm sự tiện nghi vượt bậc của chiếc xe thế hệ mới",
  "Tự tin bước ra thế giới với tâm thế vững vàng của người làm chủ cuộc sống",
  "Khẳng định sự lựa chọn sáng suốt và đúng đắn nhất cho nhu cầu của bản thân"
];

console.log("Saving full 5-industry files...");

// Next, let's create BH, TC, NH in the generator!
